(function(){
const LANGS={pt:{name:'Português',map:{'Procurar produtos...':'Procurar produtos...','Ver a loja':'Ver a loja','Explore por categoria':'Explore por categoria','Ver tudo':'Ver tudo','Adicionar ao carrinho':'Adicionar ao carrinho','Carrinho':'Carrinho','Conta':'Conta','Blog':'Blog','Produto':'Produto','Disponível':'Disponível','Indisponível':'Indisponível','Dados de contacto':'Dados de contacto','Morada de entrega':'Morada de entrega','Forma de pagamento':'Forma de pagamento'}},en:{name:'English',map:{'Procurar produtos...':'Search products...','Ver a loja':'Shop now','Explore por categoria':'Explore by category','Ver tudo':'View all','Adicionar ao carrinho':'Add to cart','Carrinho':'Cart','Conta':'Account','Blog':'Journal','Produto':'Product','Disponível':'In stock','Indisponível':'Unavailable','Dados de contacto':'Contact details','Morada de entrega':'Shipping address','Forma de pagamento':'Payment method'}},es:{name:'Español',map:{'Procurar produtos...':'Buscar productos...','Ver a loja':'Ver tienda','Explore por categoria':'Explorar por categoría','Ver tudo':'Ver todo','Adicionar ao carrinho':'Añadir al carrito','Carrinho':'Carrito','Conta':'Cuenta','Blog':'Blog','Produto':'Producto','Disponível':'Disponible','Indisponível':'No disponible','Dados de contacto':'Datos de contacto','Morada de entrega':'Dirección de entrega','Forma de pagamento':'Método de pago'}},fr:{name:'Français',map:{'Procurar produtos...':'Rechercher des produits...','Ver a loja':'Voir la boutique','Explore por categoria':'Explorer par catégorie','Ver tudo':'Tout voir','Adicionar ao carrinho':'Ajouter au panier','Carrinho':'Panier','Conta':'Compte','Blog':'Journal','Produto':'Produit','Disponível':'En stock','Indisponível':'Indisponible','Dados de contacto':'Coordonnées','Morada de entrega':'Adresse de livraison','Forma de pagamento':'Mode de paiement'}}};
const CURRENCIES={EUR:{name:'Euro',symbol:'€'},USD:{name:'US Dollar',symbol:'$'},GBP:{name:'British Pound',symbol:'£'},CHF:{name:'Swiss Franc',symbol:'CHF'},CAD:{name:'Canadian Dollar',symbol:'CA$'},BRL:{name:'Brazilian Real',symbol:'R$'},MXN:{name:'Mexican Peso',symbol:'MX$'},CLP:{name:'Chilean Peso',symbol:'CLP$'},COP:{name:'Colombian Peso',symbol:'COP$'},PLN:{name:'Polish Zloty',symbol:'zł'},SEK:{name:'Swedish Krona',symbol:'kr'},DKK:{name:'Danish Krone',symbol:'kr'},NOK:{name:'Norwegian Krone',symbol:'kr'},CZK:{name:'Czech Koruna',symbol:'Kč'},RON:{name:'Romanian Leu',symbol:'lei'},ZAR:{name:'South African Rand',symbol:'R'},AOA:{name:'Kwanza',symbol:'Kz'}};
let rates={EUR:1};
function lang(){return localStorage.getItem('lumina_lang')||((navigator.language||'pt').slice(0,2)) in LANGS?(navigator.language||'pt').slice(0,2):'pt'}
function currency(){return localStorage.getItem('lumina_currency')||({PT:'EUR',ES:'EUR',FR:'EUR',DE:'EUR',IT:'EUR',GB:'GBP',US:'USD',CA:'CAD',BR:'BRL',MX:'MXN',AO:'AOA'}[localStorage.getItem('lumina_country')]||'EUR')}
function money(eur,cur=currency()){const rate=Number(rates[cur]||1);const value=Number(eur||0)*rate;return new Intl.NumberFormat(lang()==='pt'?'pt-PT':lang()==='fr'?'fr-FR':lang()==='es'?'es-ES':'en-US',{style:'currency',currency:cur,maximumFractionDigits:['CLP','COP','JPY','AOA'].includes(cur)?0:2}).format(value)}
async function loadRates(){try{const base=(window.LUMINA_API_BASE_URL||'https://lojaonline-backend.onrender.com/api').replace(/\/$/,'');const r=await fetch(base+'/config/public');if(r.ok){const d=await r.json();rates=d.rates||rates;window.LUMINA_RATES=rates;window.LUMINA_FX_UPDATED_AT=d.updatedAt||null;document.dispatchEvent(new CustomEvent('lumina:rates'));}}catch(e){console.warn('FX indisponível; preços mantidos em EUR.')}}

function controls(){if(document.querySelector('.lumina-localizacao'))return;const box=document.createElement('div');box.className='lumina-localizacao';box.innerHTML='<label><span class="sr-only">Language</span><select id="lumina-lang"><option value="pt">PT</option><option value="en">EN</option><option value="es">ES</option><option value="fr">FR</option></select></label><label><span class="sr-only">Currency</span><select id="lumina-currency"><option>EUR</option><option>USD</option><option>GBP</option><option>CHF</option><option>CAD</option><option>BRL</option><option>MXN</option><option>CLP</option><option>COP</option><option>PLN</option><option>SEK</option><option>DKK</option><option>NOK</option><option>CZK</option><option>RON</option><option>ZAR</option><option>AOA</option></select></label>';const target=document.querySelector('.acoes-header');if(target)target.prepend(box);box.querySelector('#lumina-lang').value=lang();box.querySelector('#lumina-currency').value=currency();box.querySelector('#lumina-lang').onchange=e=>{localStorage.setItem('lumina_lang',e.target.value);location.reload()};box.querySelector('#lumina-currency').onchange=e=>{localStorage.setItem('lumina_currency',e.target.value);location.reload()}}
window.LUMINA={lang,currency,money,get rates(){return rates}};document.addEventListener('DOMContentLoaded',()=>{controls();applyText();loadRates()});document.addEventListener('lumina:rates',()=>window.dispatchEvent(new Event('lumina:currency-ready')));})();
